[metadata]
name = awesomepyutil
version = 0.0.2
author = Indranil Pal
author_email = indra.tutun@gmail.com
description = An awesome Python package
long_description = file: README.md, LICENSE
long_description_content_type = text/markdown
keywords = GCP, AWS, AZURE, Snowflake, Office365, Cloud, Data Pipeline, ETL, ELT, SQL, Python
url = https://gitlab.com/easycloudapi
project_urls =
    Bug Tracker = https://github.com/TheDataFestAI/awesomepyutil/issues
    repository = https://github.com/TheDataFestAI/awesomepyutil

classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
install_requires = file: requirements.txt

[options.packages.find]
where = src
; include = *